
platform :ios, '9.0'

target 'Skintect' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'SwiftyJSON'
pod 'Alamofire'
pod 'SVProgressHUD'

end
